// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TestReverseEngineer.Models
{
    [Table("tabItem")]
    public partial class tabItem
    {
        public tabItem()
        {
            tabOrderLineItems = new HashSet<tabOrderLineItem>();
            tabReviews = new HashSet<tabReview>();
        }

        [Key]
        public int ItemID { get; set; }
        public double? UnitPrice { get; set; }
        public int Sold { get; set; }
        [StringLength(500)]
        public string ProductImage { get; set; }
        [StringLength(70)]
        public string DigitalSignature { get; set; }
        [StringLength(250)]
        public string Description { get; set; }
        [StringLength(20)]
        public string ImageName { get; set; }
        public int? CreatedBy { get; set; }

        [ForeignKey("CreatedBy")]
        [InverseProperty("tabItems")]
        public virtual tabCustomer CreatedByNavigation { get; set; }
        [InverseProperty("ItemNameNavigation")]
        public virtual ICollection<tabOrderLineItem> tabOrderLineItems { get; set; }
        [InverseProperty("OnItemNavigation")]
        public virtual ICollection<tabReview> tabReviews { get; set; }
    }
}