// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TestReverseEngineer.Models
{
    [Table("tabOrder")]
    public partial class tabOrder
    {
        public tabOrder()
        {
            tabOrderLineItems = new HashSet<tabOrderLineItem>();
        }

        [Key]
        public int OrderID { get; set; }
        [Column(TypeName = "date")]
        public DateTime? OrderDate { get; set; }
        public int? CustomerFK { get; set; }
        public int Processed { get; set; }

        [ForeignKey("CustomerFK")]
        [InverseProperty("tabOrders")]
        public virtual tabCustomer CustomerFKNavigation { get; set; }
        [InverseProperty("OrderNameNavigation")]
        public virtual ICollection<tabOrderLineItem> tabOrderLineItems { get; set; }
    }
}