// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TestReverseEngineer.Models
{
    [Table("tabReview")]
    public partial class tabReview
    {
        [Key]
        public int ReviewID { get; set; }
        [Column(TypeName = "date")]
        public DateTime? Date { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string Review { get; set; }
        public int? ReviewBy { get; set; }
        public int? OnItem { get; set; }

        [ForeignKey("OnItem")]
        [InverseProperty("tabReviews")]
        public virtual tabItem OnItemNavigation { get; set; }
        [ForeignKey("ReviewBy")]
        [InverseProperty("tabReviews")]
        public virtual tabCustomer ReviewByNavigation { get; set; }
    }
}