//// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
//#nullable disable
//using System;
//using System.Collections.Generic;
//using System.ComponentModel.DataAnnotations;
//using System.ComponentModel.DataAnnotations.Schema;
//using Microsoft.EntityFrameworkCore;

//namespace TestReverseEngineer.Models
//{
//    [Table("tabUser")]
//    public partial class tabUser
//    {
//        [Key]
//        public int UserID { get; set; }
        
//        [StringLength(50)]
//        [Unicode(false)]
//        [RegularExpression(@"^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$", ErrorMessage = "Please use a valid email")]
//        public string Email { get; set; }
        
//        [Column(TypeName = "date")]
//        public DateTime? DoB { get; set; }
        
//        [Column(TypeName = "date")]
//        public DateTime? SignupDate { get; set; }
//        public int? LoggedIn { get; set; }
        
//        [Required]
//        [StringLength(255)]
//        [RegularExpression(@"^[a-zA-Z0-9\*\$]+$", ErrorMessage = "Letters, digits, *, $")]
//        public string Password { get; set; }

//        [Required]
//        [StringLength(50)]
//        [RegularExpression(@"^[a-zA-Z]+\s[a-zA-Z]+$", ErrorMessage = "First and Last Name; Upper and lower case letters")]
//        [Display(Name = "Full Name", Prompt = "First and Last Name")]
//        public string FullName { get; set; }
//    }
//}