// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace TestReverseEngineer.Models
{
    public partial class Team108DBContext : DbContext
    {
        public Team108DBContext()
        {
        }

        public Team108DBContext(DbContextOptions<Team108DBContext> options)
            : base(options)
        {
        }

        public virtual DbSet<tabCustomer> tabCustomers { get; set; }
        public virtual DbSet<tabItem> tabItems { get; set; }
        public virtual DbSet<tabOrder> tabOrders { get; set; }
        public virtual DbSet<tabOrderLineItem> tabOrderLineItems { get; set; }
        public virtual DbSet<tabReview> tabReviews { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<tabCustomer>(entity =>
            {
                entity.Property(e => e.Role).IsFixedLength();
            });

            modelBuilder.Entity<tabItem>(entity =>
            {
                entity.HasOne(d => d.CreatedByNavigation)
                    .WithMany(p => p.tabItems)
                    .HasForeignKey(d => d.CreatedBy)
                    .HasConstraintName("FK_tabItem_tabCustomer");
            });

            modelBuilder.Entity<tabOrder>(entity =>
            {
                entity.Property(e => e.OrderDate).HasDefaultValueSql("(getdate())");

                entity.HasOne(d => d.CustomerFKNavigation)
                    .WithMany(p => p.tabOrders)
                    .HasForeignKey(d => d.CustomerFK)
                    .HasConstraintName("FK_tabOrder_tabCustomer");
            });

            modelBuilder.Entity<tabOrderLineItem>(entity =>
            {
                entity.HasOne(d => d.ItemNameNavigation)
                    .WithMany(p => p.tabOrderLineItems)
                    .HasForeignKey(d => d.ItemName)
                    .HasConstraintName("FK_tabOrderLineItem_tabItem");

                entity.HasOne(d => d.OrderNameNavigation)
                    .WithMany(p => p.tabOrderLineItems)
                    .HasForeignKey(d => d.OrderName)
                    .HasConstraintName("FK_tabOrderLineItem_tabOrder");
            });

            modelBuilder.Entity<tabReview>(entity =>
            {
                entity.HasOne(d => d.OnItemNavigation)
                    .WithMany(p => p.tabReviews)
                    .HasForeignKey(d => d.OnItem)
                    .HasConstraintName("FK_tabReview_tabItem");

                entity.HasOne(d => d.ReviewByNavigation)
                    .WithMany(p => p.tabReviews)
                    .HasForeignKey(d => d.ReviewBy)
                    .HasConstraintName("FK_tabReview_tabCustomer");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}